# SciPy Library


collection of mathematical algorithms and convenience functions built on NumPy

### Install Scipy

If you already have Python, you can install Scipy with:

conda install scipy or pip install scipy

### Import Scipy

In [1]:
import scipy as sp

### Constants 


Physical and mathematical constants and units

In [2]:
from scipy import constants

### value


Value in physical_constants indexed by key

### unit 

Unit in physical_constants indexed by key

In [3]:
help(constants.value)

Help on function value in module scipy.constants._codata:

value(key: 'str') -> 'float'
    Value in physical_constants indexed by key
    
    Parameters
    ----------
    key : Python string or unicode
        Key in dictionary `physical_constants`
    
    Returns
    -------
    value : float
        Value in `physical_constants` corresponding to `key`
    
    Examples
    --------
    >>> from scipy import constants
    >>> constants.value(u'elementary charge')
    1.602176634e-19



In [4]:
help(constants.unit)

Help on function unit in module scipy.constants._codata:

unit(key: 'str') -> 'str'
    Unit in physical_constants indexed by key
    
    Parameters
    ----------
    key : Python string or unicode
        Key in dictionary `physical_constants`
    
    Returns
    -------
    unit : Python string
        Unit in `physical_constants` corresponding to `key`
    
    Examples
    --------
    >>> from scipy import constants
    >>> constants.unit(u'proton mass')
    'kg'



### Mathematical and Physical constants

In [5]:
## proton charge
## p = 1.602176634×10−19 kilograms 
constants.value('elementary charge')

1.602176634e-19

In [6]:
## proton mass unit
constants.unit('proton mass')

'kg'

In [7]:
## electron charge
## e = 9.10938356 × 10-31 kilograms
constants.value('electron mass')

9.1093837015e-31

In [8]:
## electron mass unit
constants.unit('electron mass')

'kg'

In [9]:
## atomic charge
## a = 1.6605390666e-27 kilograms
constants.value('atomic mass constant')

1.6605390666e-27

In [10]:
## neutron charge
## n = 1.67492749804e-27 kilograms
constants.value('neutron mass')

1.67492749804e-27

In [11]:
## neutron mass unit
constants.unit('neutron mass')

'kg'

In [12]:
## standard atmosphere value 
## ap = 101325 
constants.value('standard atmosphere')

101325.0

In [13]:
## standard atmosphere unit 
## ap = 101325 Pa
constants.unit('standard atmosphere')

'Pa'

In [14]:
## Planck constant value 
## ap = 6.62607015e-34 
constants.value('Planck constant')

6.62607015e-34

In [15]:
## Newtonian constant of gravitation value
## G = 6.6743e-11
constants.value('Newtonian constant of gravitation')

6.6743e-11

In [16]:
## Newtonian constant of gravitation unit
## G = 6.6743e-11 m^3 kg^-1 s^-2
constants.unit('Newtonian constant of gravitation')

'm^3 kg^-1 s^-2'

### find

Return list of physical_constant keys containing a given string

In [17]:
from scipy.constants import find, physical_constants
find('boltzmann')

['Boltzmann constant',
 'Boltzmann constant in Hz/K',
 'Boltzmann constant in eV/K',
 'Boltzmann constant in inverse meter per kelvin',
 'Stefan-Boltzmann constant']

In [18]:
find('ele')

['Compton wavelength',
 'Wien wavelength displacement law constant',
 'alpha particle-electron mass ratio',
 'atomic mass unit-electron volt relationship',
 'atomic unit of electric dipole mom.',
 'atomic unit of electric field',
 'atomic unit of electric field gradient',
 'atomic unit of electric polarizability',
 'atomic unit of electric potential',
 'atomic unit of electric quadrupole mom.',
 'classical electron radius',
 'deuteron-electron mag. mom. ratio',
 'deuteron-electron mass ratio',
 'electron charge to mass quotient',
 'electron g factor',
 'electron gyromag. ratio',
 'electron gyromag. ratio in MHz/T',
 'electron mag. mom.',
 'electron mag. mom. anomaly',
 'electron mag. mom. to Bohr magneton ratio',
 'electron mag. mom. to nuclear magneton ratio',
 'electron mass',
 'electron mass energy equivalent',
 'electron mass energy equivalent in MeV',
 'electron mass in u',
 'electron molar mass',
 'electron relative atomic mass',
 'electron to alpha particle mass ratio',
 'electr

### convert_temperature 


Convert from a temperature scale to another one among Celsius, Kelvin, Fahrenheit, and Rankine scales

In [19]:
from scipy.constants import convert_temperature
import numpy as np

In [20]:
tmp = convert_temperature(np.array([-40, 40]), 'Celsius', 'Kelvin')
tmp

array([233.15, 313.15])

### Linear Algebra " scipy.linalg "

In [21]:
import numpy as np
A = np.mat('[1 2;3 4]')
A

matrix([[1, 2],
        [3, 4]])

In [22]:
A.I

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [23]:
B = np.mat('[5 6]')
B

matrix([[5, 6]])

In [24]:
B.T

matrix([[5],
        [6]])

In [25]:
A*B.T

matrix([[17],
        [39]])

In [26]:
import numpy as np
from scipy import linalg
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [27]:
linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [28]:
B = np.array([[5,6]])
B

array([[5, 6]])

In [29]:
B.T

array([[5],
       [6]])

In [30]:
A*B

array([[ 5, 12],
       [15, 24]])

In [31]:
A.dot(B.T)

array([[17],
       [39]])

In [32]:
X = np.array([[1,3,5],[2,5,1],[2,3,8]])
X

array([[1, 3, 5],
       [2, 5, 1],
       [2, 3, 8]])

In [33]:
linalg.inv(X)

array([[-1.48,  0.36,  0.88],
       [ 0.56,  0.08, -0.36],
       [ 0.16, -0.12,  0.04]])

In [34]:
X.dot(linalg.inv(X))

array([[ 1.00000000e+00, -1.11022302e-16, -6.24500451e-17],
       [ 3.05311332e-16,  1.00000000e+00,  1.87350135e-16],
       [ 2.22044605e-16, -1.11022302e-16,  1.00000000e+00]])

#### Solving a linear system

solve two equation 
 
 x + 2y = 5
 
 3x + 4y = 6

In [35]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [36]:
b = np.array([[5], [6]])
b

array([[5],
       [6]])

In [37]:
linalg.inv(a).dot(b) 

array([[-4. ],
       [ 4.5]])

In [38]:
np.linalg.solve(a, b)

array([[-4. ],
       [ 4.5]])

solve three equation 

x + 3y + 5z = 10

2x + 5y + z = 8

2x + 3y + 8z = 3

In [39]:
A = np.array([1,3,5,2,5,1,2,3,8]).reshape(3,3)
A

array([[1, 3, 5],
       [2, 5, 1],
       [2, 3, 8]])

In [40]:
B = np.array([10,8,3]).reshape(3,1)
B

array([[10],
       [ 8],
       [ 3]])

In [41]:
z = np.linalg.solve(A,B)
z

array([[-9.28],
       [ 5.16],
       [ 0.76]])

In [42]:
linalg.inv(A).dot(B)

array([[-9.28],
       [ 5.16],
       [ 0.76]])

### Finding the determinant

In [43]:
x = np.array([1,3,5,2,5,1,2,3,8]).reshape(3,3)
x

array([[1, 3, 5],
       [2, 5, 1],
       [2, 3, 8]])

In [44]:
linalg.det(A)

-25.000000000000004

In [45]:
y = np.array([1,2,3,4]).reshape(2,2)
y

array([[1, 2],
       [3, 4]])

In [46]:
linalg.det(y)

-2.0

Eigenvalues and eigenvectors

The eigenvalue-eigenvector problem is one of the most commonly employed linear algebra operations.

In one popular form, the eigenvalue-eigenvector problem is to find for some square matrix 
 

In [47]:
linalg.eig(y)

(array([-0.37228132+0.j,  5.37228132+0.j]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [48]:
linalg.eig(x)

(array([10.5540456 +0.j, -0.5873064 +0.j,  4.03326081+0.j]),
 array([[-0.51686204, -0.94195144,  0.11527992],
        [-0.32845853,  0.31778071, -0.81936883],
        [-0.79054957,  0.10836468,  0.56155611]]))